output_dir: /data/nasif12/home_if12/tsi/output/enformer
debug: true

test:
  dataloader_size: 10
  is_random_enformer: false

vcf:
  path: /s/project/rep/processed/training_results_v14/gtex_v8_old_dna/distinct_variants.valid_snp_indel.vcf/
  variant_upstream_tss: 2000
  variant_downstream_tss: 500

genome:
  gtf_file: /s/genomes/Gencode/Gencode_human/release_40/GRCh37_mapping/gencode.v40lift37.annotation.gtf.gz
  fasta_file: /s/genomes/Gencode/Gencode_human/release_40/GRCh37_mapping/GRCh37.primary_assembly.genome.fa
  isoform_file: /s/project/abexp_veff/paper_submission/zenodo_user_update1/gtex_v8_isoform_proportions.tsv
  canonical_only: false
  protein_coding_only: true
  chromosomes:
    - chrY
    - chr21

enformer:
  shift: 43
  batch_size: 2
  num_output_bins: 21
  tissue_mapper:
    expression_path: /s/project/rep/processed/training_results_v14/general/gtex_transcript_tpms.zarr/
    tracks_path: assets/human_cage_dnase_enformer_tracks.yaml
    cv: 5
    nbins: 3