genomes:
  GRCh37:
    gtf_file: /s/genomes/Gencode/Gencode_human/release_40/GRCh37_mapping/gencode.v40lift37.annotation.gtf.gz
    fasta_file: /s/genomes/Gencode/Gencode_human/release_40/GRCh37_mapping/GRCh37.primary_assembly.genome.fa
    canonical_only: false
    protein_coding_only: true
    chromosomes:
      - chr1
      - chr2
      - chr3
      - chr4
      - chr5
      - chr6
      - chr7
      - chr8
      - chr9
      - chr10
      - chr11
      - chr12
      - chr13
      - chr14
      - chr15
      - chr16
      - chr17
      - chr18
      - chr19
      - chr20
      - chr21
      - chr22
      - chrX
      - chrY


vcfs:
  gtexv8_2000-500:
    path: /s/project/rep/processed/training_results_v14/distinct_variants.valid_snp_indel.vcf.restored/distinct_variants.valid_snp_indel.vcf/
    variant_upstream_tss: 2000
    variant_downstream_tss: 500

enformer:
  models:
    short:
      shift: 43
      batch_size: 2
      num_output_bins: 21
    complete:
      shift: 43
      batch_size: 2
      num_output_bins: 896

  references:
    GRCh37_short:
      genome: GRCh37
      model: short

  alternatives:
    GRCh37_short__gtexv8_2000-500:
      reference: GRCh37_short
      vcf: gtexv8_2000-500

  mappers:
    elasticnet_dnase_cage_gtexv8:
      num_agg_bins: 3
      expression_path: /s/project/rep/processed/training_results_v15/general/gtex_transcript_tpms.zarr/
      tracks_path: assets/enformer_tracks/human_cage_dnase_enformer_tracks.yaml
      type: ElasticNet
      params:
        cv: 5
        max_iter: 1000
    elasticnet_cage_gtexv8:
      num_agg_bins: 3
      expression_path: /s/project/rep/processed/training_results_v15/general/gtex_transcript_tpms.zarr/
      tracks_path: assets/enformer_tracks/human_cage_nonuniversal_enformer_tracks.yaml
      type: ElasticNet
      params:
        cv: 5
        max_iter: 1000
    elasticnet_dnase_gtexv8:
      num_agg_bins: 3
      expression_path: /s/project/rep/processed/training_results_v15/general/gtex_transcript_tpms.zarr/
      tracks_path: assets/enformer_tracks/human_dnase_enformer_tracks.yaml
      type: ElasticNet
      params:
        cv: 5
        max_iter: 1000
    elasticnet_total_gtexv8:
      num_agg_bins: 3
      expression_path: /s/project/rep/processed/training_results_v15/general/gtex_transcript_tpms.zarr/
      tracks_path: assets/enformer_tracks/human_enformer_tracks.yaml
      type: ElasticNet
      params:
        cv: 5
        max_iter: 1000
    lightgbm_dnase_cage_gtexv8:
      num_agg_bins: 3
      expression_path: /s/project/rep/processed/training_results_v15/general/gtex_transcript_tpms.zarr/
      tracks_path: assets/enformer_tracks/human_cage_dnase_enformer_tracks.yaml
      type: LightGBM
    lightgbm_cage_gtexv8:
      num_agg_bins: 3
      expression_path: /s/project/rep/processed/training_results_v15/general/gtex_transcript_tpms.zarr/
      tracks_path: assets/enformer_tracks/human_cage_nonuniversal_enformer_tracks.yaml
      type: LightGBM
    lightgbm_total_gtexv8:
      num_agg_bins: 3
      expression_path: /s/project/rep/processed/training_results_v15/general/gtex_transcript_tpms.zarr/
      tracks_path: assets/enformer_tracks/human_enformer_tracks.yaml
      type: LightGBM
    ridge_dnase_cage_gtexv8:
      num_agg_bins: 3
      expression_path: /s/project/rep/processed/training_results_v15/general/gtex_transcript_tpms.zarr/
      tracks_path: assets/enformer_tracks/human_cage_dnase_enformer_tracks.yaml
      type: Ridge
    ridge_cage_gtexv8:
      num_agg_bins: 3
      expression_path: /s/project/rep/processed/training_results_v15/general/gtex_transcript_tpms.zarr/
      tracks_path: assets/enformer_tracks/human_cage_nonuniversal_enformer_tracks.yaml
      type: Ridge
    ridge_total_gtexv8:
      num_agg_bins: 3
      expression_path: /s/project/rep/processed/training_results_v15/general/gtex_transcript_tpms.zarr/
      tracks_path: assets/enformer_tracks/human_enformer_tracks.yaml
      type: Ridge
