runs:
  # Enformer elasticnet
  enformer_gtexv8_elasticnet_total_logsumexp:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: elasticnet_total_gtexv8
    aggregation_mode: logsumexp
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_elasticnet_dnase_cage_logsumexp:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: elasticnet_dnase_cage_gtexv8
    aggregation_mode: logsumexp
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_elasticnet_cage_logsumexp:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: elasticnet_cage_gtexv8
    aggregation_mode: logsumexp
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_elasticnet_dnase_logsumexp:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: elasticnet_dnase_gtexv8
    aggregation_mode: logsumexp
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_elasticnet_total_canonical:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: elasticnet_total_gtexv8
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_elasticnet_dnase_cage_canonical:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: elasticnet_dnase_cage_gtexv8
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_elasticnet_cage_canonical:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: elasticnet_cage_gtexv8
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_elasticnet_dnase_canonical:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: elasticnet_dnase_gtexv8
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null
  # Enformer lightgbm
  enformer_gtexv8_lightgbm_total_logsumexp:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: lightgbm_total_gtexv8
    aggregation_mode: logsumexp
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_lightgbm_dnase_cage_logsumexp:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: lightgbm_dnase_cage_gtexv8
    aggregation_mode: logsumexp
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_lightgbm_cage_logsumexp:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: lightgbm_cage_gtexv8
    aggregation_mode: logsumexp
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_lightgbm_total_canonical:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: lightgbm_total_gtexv8
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_lightgbm_dnase_cage_canonical:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: lightgbm_dnase_cage_gtexv8
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_lightgbm_cage_canonical:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: lightgbm_cage_gtexv8
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null
  # Enformer ridge
  enformer_gtexv8_ridge_total_logsumexp:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: ridge_total_gtexv8
    aggregation_mode: logsumexp
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_ridge_dnase_cage_logsumexp:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: ridge_dnase_cage_gtexv8
    aggregation_mode: logsumexp
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_ridge_cage_logsumexp:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: ridge_cage_gtexv8
    aggregation_mode: logsumexp
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_ridge_total_canonical:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: ridge_total_gtexv8
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_ridge_dnase_cage_canonical:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: ridge_dnase_cage_gtexv8
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null
  enformer_gtexv8_ridge_cage_canonical:
    predictor: enformer
    alternative: GRCh37_short__gtexv8_2000-500
    mapper: ridge_cage_gtexv8
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null

comparisons:
  enformer_elasticnet:
    - enformer_gtexv8_elasticnet_dnase_cage_logsumexp
    - enformer_gtexv8_elasticnet_cage_logsumexp
    - enformer_gtexv8_elasticnet_dnase_cage_canonical
    - enformer_gtexv8_elasticnet_cage_canonical
    - enformer_gtexv8_elasticnet_dnase_canonical
    - enformer_gtexv8_elasticnet_dnase_logsumexp
    - enformer_gtexv8_elasticnet_total_logsumexp
    - enformer_gtexv8_elasticnet_total_canonical
      #  enformer_lightgbm:
      #    - enformer_gtexv8_lightgbm_dnase_cage_logsumexp
      #    - enformer_gtexv8_lightgbm_cage_logsumexp
      #    - enformer_gtexv8_lightgbm_dnase_cage_canonical
      #    - enformer_gtexv8_lightgbm_cage_canonical
      #    - enformer_gtexv8_lightgbm_total_logsumexp
      #    - enformer_gtexv8_lightgbm_total_canonical
      #  enformer_ridge:
      #    - enformer_gtexv8_ridge_dnase_cage_logsumexp
      #    - enformer_gtexv8_ridge_cage_logsumexp
      #    - enformer_gtexv8_ridge_dnase_cage_canonical
      #    - enformer_gtexv8_ridge_cage_canonical
      #    - enformer_gtexv8_ridge_total_logsumexp
      #    - enformer_gtexv8_ridge_total_canonical
  enformer_tissue_mapper_model:
    - enformer_gtexv8_elasticnet_cage_canonical
    - enformer_gtexv8_lightgbm_cage_canonical
    - enformer_gtexv8_ridge_cage_canonical


