# the path to the output folder
output_path: /s/project/promoter_prediction/kipoi_expression_prediction
enformer_use_gpu: true
aparent2_use_gpu: false

benchmarks:
  complete:
    genotypes_path: /s/project/rep/processed/training_results_v15/gtex_v8_old_dna/private_variants.parquet/rare_variants.vcf.parquet/**/*.parquet
    annotation_path: /s/project/rep/processed/training_results_v15/gtex_benchmark_with_annotation.parquet/*.parquet
    folds_path: /s/project/rep/processed/training_results_v15/gtex_v8_old_dna/folds.parquet
    fdr_cutoff: 0.2
    tissues:
      - "Adipose - Subcutaneous"
      - "Adipose - Visceral (Omentum)"
      - "Adrenal Gland"
      - "Artery - Aorta"
      - "Artery - Coronary"
      - "Artery - Tibial"
      - "Brain - Amygdala"
      - "Brain - Anterior cingulate cortex (BA24)"
      - "Brain - Caudate (basal ganglia)"
      - "Brain - Cerebellar Hemisphere"
      - "Brain - Cerebellum"
      - "Brain - Cortex"
      - "Brain - Frontal Cortex (BA9)"
      - "Brain - Hippocampus"
      - "Brain - Hypothalamus"
      - "Brain - Nucleus accumbens (basal ganglia)"
      - "Brain - Putamen (basal ganglia)"
      - "Brain - Spinal cord (cervical c-1)"
      - "Brain - Substantia nigra"
      - "Breast - Mammary Tissue"
      - "Cells - EBV-transformed lymphocytes"
      - "Cells - Cultured fibroblasts"
      - "Colon - Sigmoid"
      - "Colon - Transverse"
      - "Esophagus - Gastroesophageal Junction"
      - "Esophagus - Mucosa"
      - "Esophagus - Muscularis"
      - "Heart - Atrial Appendage"
      - "Heart - Left Ventricle"
      - "Kidney - Cortex"
      - "Liver"
      - "Lung"
      - "Minor Salivary Gland"
      - "Muscle - Skeletal"
      - "Nerve - Tibial"
      - "Ovary"
      - "Pancreas"
      - "Pituitary"
      - "Prostate"
      - "Skin - Not Sun Exposed (Suprapubic)"
      - "Skin - Sun Exposed (Lower leg)"
      - "Small Intestine - Terminal Ileum"
      - "Spleen"
      - "Stomach"
      - "Testis"
      - "Thyroid"
      - "Uterus"
      - "Vagina"
      - "Whole Blood"
  tss_2500:
    genotypes_path: /s/project/rep/processed/training_results_v15/gtex_v8_old_dna/private_variants.parquet/rare_variants.vcf.parquet/**/*.parquet
    annotation_path: /s/project/promoter_prediction/kipoi_expression_prediction/new_benchmarks/tss_benchmark.parquet
    folds_path: /s/project/rep/processed/training_results_v15/gtex_v8_old_dna/folds.parquet
    fdr_cutoff: 0.2
    tissues:
      - "Adipose - Subcutaneous"
      - "Adipose - Visceral (Omentum)"
      - "Adrenal Gland"
      - "Artery - Aorta"
      - "Artery - Coronary"
      - "Artery - Tibial"
      - "Brain - Amygdala"
      - "Brain - Anterior cingulate cortex (BA24)"
      - "Brain - Caudate (basal ganglia)"
      - "Brain - Cerebellar Hemisphere"
      - "Brain - Cerebellum"
      - "Brain - Cortex"
      - "Brain - Frontal Cortex (BA9)"
      - "Brain - Hippocampus"
      - "Brain - Hypothalamus"
      - "Brain - Nucleus accumbens (basal ganglia)"
      - "Brain - Putamen (basal ganglia)"
      - "Brain - Spinal cord (cervical c-1)"
      - "Brain - Substantia nigra"
      - "Breast - Mammary Tissue"
      - "Cells - EBV-transformed lymphocytes"
      - "Cells - Cultured fibroblasts"
      - "Colon - Sigmoid"
      - "Colon - Transverse"
      - "Esophagus - Gastroesophageal Junction"
      - "Esophagus - Mucosa"
      - "Esophagus - Muscularis"
      - "Heart - Atrial Appendage"
      - "Heart - Left Ventricle"
      - "Kidney - Cortex"
      - "Liver"
      - "Lung"
      - "Minor Salivary Gland"
      - "Muscle - Skeletal"
      - "Nerve - Tibial"
      - "Ovary"
      - "Pancreas"
      - "Pituitary"
      - "Prostate"
      - "Skin - Not Sun Exposed (Suprapubic)"
      - "Skin - Sun Exposed (Lower leg)"
      - "Small Intestine - Terminal Ileum"
      - "Spleen"
      - "Stomach"
      - "Testis"
      - "Thyroid"
      - "Uterus"
      - "Vagina"
      - "Whole Blood"
  pas_2500:
    genotypes_path: /s/project/rep/processed/training_results_v15/gtex_v8_old_dna/private_variants.parquet/rare_variants.vcf.parquet/**/*.parquet
    annotation_path: /s/project/promoter_prediction/kipoi_expression_prediction/new_benchmarks/pas_benchmark.parquet
    folds_path: /s/project/rep/processed/training_results_v15/gtex_v8_old_dna/folds.parquet
    fdr_cutoff: 0.2
    tissues:
      - "Adipose - Subcutaneous"
      - "Adipose - Visceral (Omentum)"
      - "Adrenal Gland"
      - "Artery - Aorta"
      - "Artery - Coronary"
      - "Artery - Tibial"
      - "Brain - Amygdala"
      - "Brain - Anterior cingulate cortex (BA24)"
      - "Brain - Caudate (basal ganglia)"
      - "Brain - Cerebellar Hemisphere"
      - "Brain - Cerebellum"
      - "Brain - Cortex"
      - "Brain - Frontal Cortex (BA9)"
      - "Brain - Hippocampus"
      - "Brain - Hypothalamus"
      - "Brain - Nucleus accumbens (basal ganglia)"
      - "Brain - Putamen (basal ganglia)"
      - "Brain - Spinal cord (cervical c-1)"
      - "Brain - Substantia nigra"
      - "Breast - Mammary Tissue"
      - "Cells - EBV-transformed lymphocytes"
      - "Cells - Cultured fibroblasts"
      - "Colon - Sigmoid"
      - "Colon - Transverse"
      - "Esophagus - Gastroesophageal Junction"
      - "Esophagus - Mucosa"
      - "Esophagus - Muscularis"
      - "Heart - Atrial Appendage"
      - "Heart - Left Ventricle"
      - "Kidney - Cortex"
      - "Liver"
      - "Lung"
      - "Minor Salivary Gland"
      - "Muscle - Skeletal"
      - "Nerve - Tibial"
      - "Ovary"
      - "Pancreas"
      - "Pituitary"
      - "Prostate"
      - "Skin - Not Sun Exposed (Suprapubic)"
      - "Skin - Sun Exposed (Lower leg)"
      - "Small Intestine - Terminal Ileum"
      - "Spleen"
      - "Stomach"
      - "Testis"
      - "Thyroid"
      - "Uterus"
      - "Vagina"
      - "Whole Blood"