name: kipoi-enformer
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyarrow=15.0.0
  - numpy=1.26.4
  - pandas=2.2.1
  - pyranges=0.0.129
  - pytest=8.1.1
  - kipoiseq=0.7.1
  - cyvcf2=0.30.28
  - tensorflow-hub=0.16.1
  - tensorflow=2.15.0
  - pip
  - pip:
