output_dir: output/exp1

vcf:
  path: assets/example_files1/vcf
  variant_upstream_tss: 500
  variant_downstream_tss: 100

genome:
  gtf_file: assets/example_files1/annot.gtf.gz
  fasta_file: assets/example_files1/seq.fa

enformer:
  shift: 43
  batch_size: 2
  is_test: true
  tissue_matcher:
    tracks_path: assets/cage_nonuniversal_enformer_tracks.yaml
    model_path: assets/gtex_enformer_lm_models_pseudocount1.pkl