output_dir: output/exp1

vcfs:
  gtex_v8_old_dna:
    path: assets/example_files/vcf
    variant_upstream_tss: 500
    variant_downstream_tss: 100

genome:
  gtf_file: assets/example_files/annot.gtf
  fasta_file: assets/example_files/seq.fa

enformer:
  shift: 43
  batch_size: 2
  is_test: true
  tissue_matcher:
    tracks_path: assets/cage_nonuniversal_enformer_tracks.yaml
    model_path: assets/gtex_enformer_lm_models_pseudocount1.pkl
    num_workers: 2
  veff:
    num_workers: 2