output_dir: output/exp1

vcfs:
  gtex_v8_old_dna:
    path: /s/project/rep/processed/training_results_v14/gtex_v8_old_dna/distinct_variants.valid_snp_indel.vcf/
    variant_upstream_tss: 500
    variant_downstream_tss: 100

genome:
  gtf_file: /s/genomes/Gencode/Gencode_human/release_40/GRCh37_mapping/gencode.v40lift37.annotation.gtf.gz
  fasta_file: /s/genomes/Gencode/Gencode_human/release_40/GRCh37_mapping/gencode.v40lift37.annotation.gtf.gz

enformer:
  shift: 43
  batch_size: 5
  is_test: false
  tissue_matcher:
    tracks_path: assets/cage_nonuniversal_enformer_tracks.yaml
    model_path: assets/gtex_enformer_lm_models_pseudocount1.pkl
    num_workers: 2
  veff:
    num_workers: 2