configfile:
  - config/prod/main.yaml
  - config/prod/components.yaml
  - config/prod/enformer_runs.yaml
  - config/prod/enformer_runs_ridge_cutoffs.yaml
  - config/prod/enformer_runs_elasticnet_cutoffs.yaml
  - config/prod/aparent2_runs.yaml
  - config/prod/aparent2_cutoff_runs.yaml
  - condig/prod/lm_runs.yaml
executor: slurm
scheduler: greedy
jobs: 200
rerun-incomplete: true
rerun-triggers: mtime
keep-going: true
restart-times: 0
show-failed-logs: true
use-conda: true
conda-frontend: conda
default-resources:
  slurm_extra: "'--exclude=ouga[01-04] --no-requeue'"
  slurm_partition: lowprio
set-resources:
  enformer_predict_reference:
    slurm_extra: "'--gpus=1 --exclude=ouga[01-04] --no-requeue'"
  enformer_predict_alternative:
    slurm_extra: "'--gpus=1 --exclude=ouga[01-04] --no-requeue'"