output_dir: /data/nasif12/home_if12/tsi/output/enformer
debug: true

test:
  dataloader_size: null
  is_random_enformer: false

vcf:
  path: /s/project/rep/processed/training_results_v14/gtex_v8_old_dna/distinct_variants.valid_snp_indel.vcf/
  variant_upstream_tss: 2000
  variant_downstream_tss: 500

genome:
  gtf_file: /s/genomes/Gencode/Gencode_human/release_40/GRCh37_mapping/gencode.v40lift37.annotation.gtf.gz
  fasta_file: /s/genomes/Gencode/Gencode_human/release_40/GRCh37_mapping/GRCh37.primary_assembly.genome.fa
  canonical_only: false
  protein_coding_only: true
  chromosomes:
    - chrY
    - chr21

enformer:
  shift: 43
  batch_size: 2
  num_output_bins: 21
  tissue_matcher:
    tracks_path: assets/cage_nonuniversal_enformer_tracks.yaml
    model_path: assets/gtex_enformer_lm_models_pseudocount1.pkl
    nbins: 3