output_dir: /data/nasif12/home_if12/tsi/output/enformer
debug: true

test:
  dataloader_size: 5
  is_random_enformer: false

vcf:
  path: assets/example_files/vcf
  variant_upstream_tss: 500
  variant_downstream_tss: 100

genome:
  gtf_file: assets/example_files/annot.gtf.gz
  fasta_file: assets/example_files/seq.fa

enformer:
  shift: 43
  batch_size: 2
  is_test: true
  tissue_matcher:
    tracks_path: assets/cage_nonuniversal_enformer_tracks.yaml
    model_path: assets/gtex_enformer_lm_models_pseudocount1.pkl