output_dir: output/smk
debug: true

test:
  dataloader_size: 100
  is_random_enformer: true

vcf:
  path: assets/example_files/vcf
  variant_upstream_tss: 2000
  variant_downstream_tss: 500

genome:
  gtf_file: assets/example_files/annot.gtf.gz
  fasta_file: assets/example_files/seq.fa
  canonical_only: false
  protein_coding_only: true
  chromosomes:
    - chr21
    - chr22

enformer:
  shift: 43
  batch_size: 2
  num_output_bins: 21
  tissue_matcher:
    tracks_path: assets/cage_nonuniversal_enformer_tracks.yaml
    model_path: assets/gtex_enformer_lm_models_pseudocount1.pkl
    nbins: 3