# the path to the output folder
output_path: output/smk

debug: true
test:
  dataloader_size: 100
  is_random_enformer: true
  precomputed_enformer_mapper_path: example_files/gtex_enformer_lm_models_pseudocount1.pkl

benchmark:
  genotypes_path: example_files/gtex_samples/rare_variants.vcf.parquet
  annotation_path: example_files/gtex_samples/benchmark_with_annotation.parquet
  folds_path: example_files/gtex_samples/folds.parquet
  fdr_cutoff: 0.2

runs:
  enformer:
    veff1:
      alternative: alt1
      mapper: elasticnet_cage
      isoform_file: example_files/isoform_proportions.tsv
      aggregation_mode: logsumexp
      upstream_tss: 2000
      downstream_tss: 500
    veff2:
      alternative: alt1
      mapper: elasticnet_cage
      isoform_file: null
      aggregation_mode: canonical
      upstream_tss: 2000
      downstream_tss: 500
    veff3:
      alternative: alt1
      mapper: lightgbm_cage
      isoform_file: example_files/isoform_proportions.tsv
      aggregation_mode: logsumexp
      upstream_tss: 2000
      downstream_tss: 500
    veff4:
      alternative: alt1
      mapper: lightgbm_cage
      isoform_file: null
      aggregation_mode: canonical
      upstream_tss: 2000
      downstream_tss: 500
    veff5:
      alternative: alt1
      mapper: lightgbm_cage
      isoform_file: example_files/isoform_proportions.tsv
      aggregation_mode: logsumexp
      upstream_tss: 100
      downstream_tss: 500
    veff6:
      alternative: alt1
      mapper: lightgbm_cage
      isoform_file: null
      aggregation_mode: canonical
      upstream_tss: 100
      downstream_tss: 500
    veff7:
      alternative: alt1
      mapper: lightgbm_cage
      isoform_file: null
      aggregation_mode: canonical
      upstream_tss: null
      downstream_tss: null

comparisons:
  dev1:
    runs:
      - veff1
      - veff2
      - veff3