# the path to the output folder
output_path: /s/project/promoter_prediction/kipoi_expression_prediction

benchmark:
  genotypes_path: /s/project/rep/processed/training_results_v14/gtex_v8_old_dna/private_variants.parquet/rare_variants.vcf.parquet/**/*.parquet
  annotation_path: /s/project/rep/processed/training_results_v14/gtex_benchmark_with_annotation.parquet/*.parquet

# todo add is_canonical parameter
# todo add ridge regression
# todo run with all tracks and lightgbm
# todo lightgbm with different cutoffs if it works better
# todo ridge regression with different cutoffs
# todo canonical yes or no?

# evaluation
# PCR curve for all tissues
# Boxplot showing AUPRC across tissues
# Assess position as explanatory variable for all models


runs:
  enformer:
    gtexv8_elasticnet_dnase_cage_logsumexp:
      alternative: GRCh37_short__gtexv8_2000-500
      mapper: elasticnet_dnase_cage_gtexv8
      isoform_file: /s/project/abexp_veff/paper_submission/zenodo_user_update1/gtex_v8_isoform_proportions.tsv
      aggregation_mode: logsumexp
      upstream_tss: null
      downstream_tss: null
#    gtexv8_elasticnet_cage_logsumexp:
#      alternative: GRCh37_short__gtexv8_2000-500
#      mapper: elasticnet_cage_gtexv8
#      isoform_file: /s/project/abexp_veff/paper_submission/zenodo_user_update1/gtex_v8_isoform_proportions.tsv
#      aggregation_mode: logsumexp
#      upstream_tss: null
#      downstream_tss: null
#    gtexv8_canonical_elasticnet_dnase_cage_logsumexp:
#      alternative: GRCh37_short__gtexv8_2000-500
#      mapper: elasticnet_dnase_cage_gtexv8
#      isoform_file: null
#      aggregation_mode: canonical
#      upstream_tss: null
#      downstream_tss: null
#    gtexv8_canonical_elasticnet_cage_logsumexp:
#      alternative: GRCh37_short__gtexv8_2000-500
#      mapper: elasticnet_cage_gtexv8
#      isoform_file: null
#      aggregation_mode: canonical
#      upstream_tss: null
#      downstream_tss: null
#    gtexv8_lightgbm_dnase_cage_logsumexp:
#      alternative: GRCh37_short__gtexv8_2000-500
#      mapper: lightgbm_dnase_cage_gtexv8
#      isoform_file: /s/project/abexp_veff/paper_submission/zenodo_user_update1/gtex_v8_isoform_proportions.tsv
#      aggregation_mode: logsumexp
#      upstream_tss: null
#      downstream_tss: null
#    gtexv8_lightgbm_cage_logsumexp:
#      alternative: GRCh37_short__gtexv8_2000-500
#      mapper: lightgbm_cage_gtexv8
#      isoform_file: /s/project/abexp_veff/paper_submission/zenodo_user_update1/gtex_v8_isoform_proportions.tsv
#      aggregation_mode: logsumexp
#      upstream_tss: null
#      downstream_tss: null
#    gtexv8_canonical_lightgbm_dnase_cage_logsumexp:
#      alternative: GRCh37_short__gtexv8_2000-500
#      mapper: lightgbm_dnase_cage_gtexv8
#      isoform_file: null
#      aggregation_mode: canonical
#      upstream_tss: null
#      downstream_tss: null
#    gtexv8_canonical_lightgbm_cage_logsumexp:
#      alternative: GRCh37_short__gtexv8_2000-500
#      mapper: lightgbm_cage_gtexv8
#      isoform_file: null
#      aggregation_mode: canonical
#      upstream_tss: null
#      downstream_tss: null