name: kipoi-enformer

# extracted with
# conda list | grep -E -i -w "^$(conda env export --no-builds --from-history | awk '$1 == "-"{ if (key == "dependencies:") print $NF; next } {key=$1}' | sed 's/=.*//' | tr -s '\r\n' '|' | sed 's/|$//')\s" | awk '{ print $1 "=" $2 }' | sed 's/^/  - /'
channels:
  - conda-forge
  - bioconda
dependencies:
  - cyvcf2=0.30.28
  - kipoiseq=0.7.1
  - numpy=1.26.4
  - pandas=2.2.1
  - pip=24.0
  - pyarrow=15.0.0
  - pyranges=0.0.129
  - pytest=8.1.1
  - tensorflow=2.15.0
  - tensorflow-base=2.15.0
  - tensorflow-estimator=2.15.0
  - tensorflow-hub=0.16.1
  - ipykernel=6.28.0
  - ipywidgets=7.7.2
  - scikit-learn=1.4.1.post1
  - polars=0.20.19
  - snakemake=7.32.4
  - jupyterlab=4.1.6
  - jupytext=1.16.1
  - pip:
