name: kipoi-enformer

# extracted with
# conda list | grep -E -i -w "^$(conda env export --no-builds --from-history | awk '$1 == "-"{ if (key == "dependencies:") print $NF; next } {key=$1}' | sed 's/=.*//' | tr -s '\r\n' '|' | sed 's/|$//')\s" | awk '{ print $1 "=" $2 }' | sed 's/^/  - /'
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - cyvcf2=0.30.28
#  - kipoiseq=0.7.1
  - numpy=1.26.4
  - pandas=2.2.1
  - pip=24.0
  - pyarrow=15.0.0
  - pyranges=0.0.129
  - pytest=8.1.1
  - tensorflow-hub=0.16.1
  - ipykernel=6.28.0
  - ipywidgets=7.7.2
  - scikit-learn=1.4.1.post1
  - polars=0.20.19
  - snakemake=8.14.0
  - snakemake-executor-plugin-slurm=0.7.0
  - jupyterlab=4.1.6
  - jupytext=1.16.1
  - pytables=3.9.2
  - seaborn=0.13.2
  - matplotlib=3.8.4
  - plotnine=0.13.6
  - lightgbm=4.3.0
  - graphviz=11.0.0
  - python-graphviz=0.20.3
  - latexify-py=0.4.3
  - xarray=2024.5.0
  - zarr=2.18.2
  - jupyter_contrib_nbextensions=0.7.0
  - jupytext=1.16.1
  - r-base=4.3.3
  - r-irkernel=1.3.2
  - pip:
      - "git+https://github.com/gtsitsiridis/kipoiseq.git@master"
      - "git+https://github.com/gagneurlab/rep.git@master"
      - snakemk-util