# the path to the output folder
output_path: ../output/smk

debug: true
test:
  dataloader_size: 100
  is_random_enformer: true

# additional component configuration files to be used
configs:
  - config/components.dev.yaml

runs:
  enformer:
    gtex_v8_2000_500_elasticnet_dnase_cage_logsumexp:
      alternative: gtex_v8_2000_500
      mapper: elasticnet_dnase_cage_gtex_v8
      isoform_file: /s/project/abexp_veff/paper_submission/zenodo_user_update1/gtex_v8_isoform_proportions.tsv
      aggregation_mode: logsumexp
    gtex_v8_2000_500_elasticnet_cage_logsumexp:
      alternative: gtex_v8_2000_500
      mapper: elasticnet_cage_gtex_v8
      isoform_file: /s/project/abexp_veff/paper_submission/zenodo_user_update1/gtex_v8_isoform_proportions.tsv
      aggregation_mode: logsumexp
    gtex_v8_500_100_canonical_elasticnet_dnase_cage_logsumexp:
      alternative: gtex_v8_500_100_canonical
      mapper: elasticnet_dnase_cage_gtex_v8
      isoform_file: null
      aggregation_mode: first
    gtex_v8_500_100_canonical_elasticnet_cage_logsumexp:
      alternative: gtex_v8_500_100_canonical
      mapper: elasticnet_cage_gtex_v8
      isoform_file: null
      aggregation_mode: first
    gtex_v8_2000_500_lightgbm_dnase_cage_logsumexp:
      alternative: gtex_v8_2000_500
      mapper: lightgbm_dnase_cage_gtex_v8
      isoform_file: /s/project/abexp_veff/paper_submission/zenodo_user_update1/gtex_v8_isoform_proportions.tsv
      aggregation_mode: logsumexp
    gtex_v8_2000_500_lightgbm_cage_logsumexp:
      alternative: gtex_v8_2000_500
      mapper: lightgbm_cage_gtex_v8
      isoform_file: /s/project/abexp_veff/paper_submission/zenodo_user_update1/gtex_v8_isoform_proportions.tsv
      aggregation_mode: logsumexp
    gtex_v8_500_100_canonical_lightgbm_dnase_cage_logsumexp:
      alternative: gtex_v8_500_100_canonical
      mapper: lightgbm_dnase_cage_gtex_v8
      isoform_file: null
      aggregation_mode: first
    gtex_v8_500_100_canonical_lightgbm_cage_logsumexp:
      alternative: gtex_v8_500_100_canonical
      mapper: lightgbm_cage_gtex_v8
      isoform_file: null
      aggregation_mode: first