genomes:
  chr21_22:
    gtf_file: example_files/annot.gtf.gz
    fasta_file: example_files/seq.fa
    isoform_proportion_file: example_files/isoform_proportions.tsv
    canonical_only: false
    protein_coding_only: true
    chromosomes:
      - chr21
      - chr22

vcfs:
  chr21_22_var:
    path: example_files/vcf

apa_annotation:
  ensembl_chr21_22:
    type: ensembl
    genome: chr21_22

enformer:
  models:
    short:
      shift: 43
      batch_size: 2
      num_output_bins: 21
    complete:
      shift: 43
      batch_size: 2
      num_output_bins: 896

  references:
    ref1:
      genome: chr21_22
      model: short

  alternatives:
    alt1:
      reference: ref1
      vcf: chr21_22_var
      variant_upstream_tss: 2000
      variant_downstream_tss: 500

  mappers:
    elasticnet_cage:
      num_agg_bins: 3
      expression_path: example_files/gtex_samples/transcripts_tpms.zarr
      tracks_path: assets/enformer_tracks/human_cage_nonuniversal_enformer_tracks.yaml
      type: ElasticNet
      params:
        cv: 2
        max_iter: 1000
    lightgbm_cage:
      num_agg_bins: 3
      expression_path: example_files/gtex_samples/transcripts_tpms.zarr
      tracks_path: assets/enformer_tracks/human_cage_nonuniversal_enformer_tracks.yaml
      type: LightGBM
    ridge_cage:
      num_agg_bins: 3
      expression_path: example_files/gtex_samples/transcripts_tpms.zarr
      tracks_path: assets/enformer_tracks/human_cage_nonuniversal_enformer_tracks.yaml
      type: Ridge


aparent2:
  models:
    all_libs_resnet_no_clinvar_wt_ep_5_var_batch_size_inference_mode_no_drop:
      batch_size: 100
      path: assets/aparent2_models/aparent_all_libs_resnet_no_clinvar_wt_ep_5_var_batch_size_inference_mode_no_drop.h5

  references:
    ref1:
      model: all_libs_resnet_no_clinvar_wt_ep_5_var_batch_size_inference_mode_no_drop
      apa_annotation: ensembl_chr21_22

  alternatives:
    alt1:
      reference: ref1
      vcf: chr21_22_var
      variant_upstream_cse: 70
      variant_downstream_cse: 134