genomes:
  chr21_22:
    gtf_file: example_files/annot.gtf.gz
    fasta_file: example_files/seq.fa
    canonical_only: false
    protein_coding_only: true
    chromosomes:
      - chr21
      - chr22

vcfs:
  chr21_22_var:
    path: example_files/vcf
    variant_upstream_tss: 2000
    variant_downstream_tss: 500

enformer:
  models:
    short:
      shift: 43
      batch_size: 2
      num_output_bins: 21
    complete:
      shift: 43
      batch_size: 2
      num_output_bins: 896

  references:
    ref1:
      genome: chr21_22
      model: short

  alternatives:
    alt1:
      reference: ref1
      vcf: chr21_22_var

  mappers:
    elasticnet_cage:
      num_agg_bins: 3
      expression_path: example_files/gtex_samples/transcripts_tpms.zarr
      tracks_path: assets/enformer_tracks/cage_nonuniversal_enformer_tracks.yaml
      type: ElasticNet
      params:
        cv: 2
        max_iter: 1000
    lightgbm_cage:
      num_agg_bins: 3
      expression_path: example_files/gtex_samples/transcripts_tpms.zarr
      tracks_path: assets/enformer_tracks/cage_nonuniversal_enformer_tracks.yaml
      type: LightGBM
    ridge_cage:
      num_agg_bins: 3
      expression_path: example_files/gtex_samples/transcripts_tpms.zarr
      tracks_path: assets/enformer_tracks/cage_nonuniversal_enformer_tracks.yaml
      type: Ridge