runs:
  enformer_veff1:
    predictor: enformer
    alternative: alt1
    mapper: elasticnet_cage
    aggregation_mode: logsumexp
    upstream_tss: 2000
    downstream_tss: 500
  enformer_veff2:
    predictor: enformer
    alternative: alt1
    mapper: elasticnet_cage
    aggregation_mode: canonical
    upstream_tss: 2000
    downstream_tss: 500
  enformer_veff3:
    predictor: enformer
    alternative: alt1
    mapper: lightgbm_cage
    aggregation_mode: logsumexp
    upstream_tss: 2000
    downstream_tss: 500
  enformer_veff4:
    predictor: enformer
    alternative: alt1
    mapper: lightgbm_cage
    aggregation_mode: canonical
    upstream_tss: 2000
    downstream_tss: 500
  enformer_veff5:
    predictor: enformer
    alternative: alt1
    mapper: lightgbm_cage
    aggregation_mode: logsumexp
    upstream_tss: 100
    downstream_tss: 500
  enformer_veff6:
    predictor: enformer
    alternative: alt1
    mapper: lightgbm_cage
    aggregation_mode: canonical
    upstream_tss: 100
    downstream_tss: 500
  enformer_veff7:
    predictor: enformer
    alternative: alt1
    mapper: lightgbm_cage
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null
  enformer_veff8:
    predictor: enformer
    alternative: alt1
    mapper: ridge_cage
    aggregation_mode: canonical
    upstream_tss: null
    downstream_tss: null

comparisons:
  dev1:
    - enformer_veff1
    - enformer_veff2
    - enformer_veff3
    - enformer_veff8